eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5    # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    serviceUrl:
      defaultZone:  http://10.1.3.43:53000/eureka/
    registry-fetch-interval-seconds: 5 # 抓取服务列表
    register-with-eureka: true   #是否将自己注册到Eureka Server上，默认为true
    fetch-registry: true   #是否从Eureka Server上获取注册信息，默认为true

#wowza录制，切片
recorder:
  programGuides: /usr/local/WowzaStreamingEngine/content/prog/programGuides #储存节目单json文件的目录
  storage: /usr/local/WowzaStreamingEngine/content/prog  # 录制文件mp4存储目录
  urlPrefix:  http://10.1.3.26:8086 #wowza录制直播流的ip和端口   http://www.ttstream.com/wowza/record#livestreamrecordhttpprovider
  userName: zhenghao  #对通过Http接口控制录制任务做认证 的 用户名   http://www.ttstream.com/wowza/record#authentication
  passWord: hndtzhha  #对通过Http接口控制录制任务做认证 的 密码    http://www.ttstream.com/wowza/record#authentication
  guidesDomainName: http://prog.dianzhenkeji.com/ # 节目单域名
