eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5    # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    serviceUrl:
      defaultZone:  http://localhost:53000/eureka/
    #      defaultZone:  http://172.20.5.4:53000/eureka/
    registry-fetch-interval-seconds: 5 # 抓取服务列表
    register-with-eureka: true   #是否将自己注册到Eureka Server上，默认为true
    fetch-registry: true   #是否从Eureka Server上获取注册信息，默认为true

#wowza录制，切片
recorder:
  programGuides: E:/audioMp3/programGuides
  storage: E:/audioMp3   # 录制文件存储目录
  urlPrefix:  http://172.20.2.1:8086 #使用Http接口来录制直播流的ip:端口   http://www.ttstream.com/wowza/record#livestreamrecordhttpprovider
  userName: zhenghao  #对通过Http接口控制录制任务做认证 的 用户名   http://www.ttstream.com/wowza/record#authentication
  passWord: hndtib21  #对通过Http接口控制录制任务做认证 的 密码    http://www.ttstream.com/wowza/record#authentication
  guidesDomainName: http://prog.dianzhenkeji.com/
